version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: northfall-postgres
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: northfall_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: northfall-redis
    ports: 
      - 6379:6379

volumes:
  postgres_data:
  temp_postgres_data:
